# Generated by Django 5.0.6 on 2024-07-02 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=30)),
                ('apmaterno', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=12)),
                ('telefono_opcion', models.CharField(blank=True, max_length=12, null=True)),
                ('cod_postal', models.IntegerField()),
                ('contrasenna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cod_tela', models.IntegerField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('img_donacion', models.FileField(upload_to='fotos_donaciones')),
                ('descripcion', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
    ]
