# Generated by Django 5.0.6 on 2024-07-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_tela_alter_pedido_cod_tela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela',
            name='cod_tela',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
