# Generated by Django 5.0.6 on 2024-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_tela_cod_tela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='existencia',
            field=models.BooleanField(default=True),
        ),
    ]
