# Generated by Django 5.0.6 on 2024-07-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_tela_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
