# Generated by Django 5.0.6 on 2024-07-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_pedido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='img_donacion',
            field=models.ImageField(null=True, upload_to='donaciones'),
        ),
        migrations.AlterField(
            model_name='tela',
            name='img_tela',
            field=models.ImageField(null=True, upload_to='telas'),
        ),
    ]
