# Generated by Django 5.0.6 on 2024-07-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_donacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cod_postal',
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30, unique=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.comuna', to_field='comuna')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.comuna', to_field='comuna'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.region', to_field='region'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.region', to_field='region'),
        ),
    ]
