# Generated by Django 5.0.6 on 2024-07-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_comuna_region_remove_usuario_cod_postal_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tienda.ciudad', to_field='ciudad'),
        ),
    ]
