# Generated by Django 5.0.6 on 2024-07-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_ciudad_comuna_alter_comuna_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenna',
            new_name='contraseña',
        ),
    ]
